spring:
  application:
    name: authorization-server
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

client:
  id: ${CLIENT_ID}
  secret: ${CLIENT_SECRET}
  redirect:
    uri: ${CLIENT_REDIRECT_URI}

broker:
  queue:
    email:
      name: ${BROKER_QUEUE_EMAIL_NAME}